name: Exemplo Output
run-name: Exemplo workflow para output, executado por ${{ github.actor }}
on:
    workflow_dispatch:
jobs:
    gerando_outputs:
        runs-on: ubuntu-latest
        steps:
            - name: Gerando output com o shell
              id: exemplo-output
              run: |
                ACTION_RANDOM=$(( $RANDOM ))
                echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT

            - name: Exibindo o output da action exemplo output
              run: echo "${{ steps.exemplo-output.outputs.action_random }}"

            - name: Gerador de senha
              id: generatedpassword
              uses: aammirmirza/RandomPasswordGenerator@v1.1
              with:
                length: 15

            - name: Exibindo o output da action de password
              run: echo ${{ steps.generatedpassword.outputs.password }}


